### ISSUE TITLE
Readme not clear

### ISSUE THREAD

**Issue by palmiak** [dingo-d/wp-pest-integration-test-setup#3]
### Describe your bug

Readme file states that:
```
After that you can run the following command:

vendor/bin/wp-pest theme
```

This results in the "Command "theme" is not defined."

Everything worked fine when using `vendor/bin/wp-pest setup theme`

### Steps to Reproduce

1. Try running `vendor/bin/wp-pest theme`

### Expected behavior

Shouldn't return an error.

### Environment info

- Windows 11
- PHP 7.4.7

### Please confirm that you have searched existing issues in this repo.

Yes

**Comment by dingo-d** [comment]
Whoops wrong readme 🙈 

Thanks for the catch!
